import Head from "next/head";
import Link from "next/link";

export default function RestaurantListPage({ restaurants }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {restaurants.map((restaurant) => (
            <li key={restaurant.id}>
              <Link href={`/restaurants/${restaurant.id}`}>
                <a>{restaurant.name}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>

      <footer></footer>
    </div>
  );
}

export async function getStaticProps(context) {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/restaurants?_limit=5`
  );
  const restaurants = await res.json();

  if (!restaurants) {
    return {
      notFound: true,
    };
  }

  return {
    props: { restaurants }, // will be passed to the page component as props
  };
}
